server.port: 8088

spring:
  batch:
    jdbc:
      initialize-schme: always
    job:
      enabled: false
  datasource:
    url: jdbc:mariadb://localhost:3306/spring_batch
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: jung0@14